# Generated by Django 4.2.2 on 2023-07-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("langchainapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="langchainattr",
            name="is_active",
        ),
        migrations.AlterModelTable(
            name="langchainattr",
            table="langchainattr",
        ),
    ]
